# Generated by Django 5.2.1 on 2025-05-30 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the each object.', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authentication_type', models.CharField(blank=True, max_length=50, null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_ip', models.GenericIPAddressField()),
                ('request_domain', models.CharField(max_length=255)),
                ('original_file_path', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('modified_file_path', models.FileField(blank=True, null=True, upload_to='uploads/modified/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('finalized_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('is_ai_processed', models.BooleanField(default=False)),
                ('is_client_fetched_response', models.BooleanField(default=False)),
                ('is_batched_call', models.BooleanField(default=True)),
                ('doc_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'PDF'), (1, 'WORD'), (2, 'EXCEL'), (3, 'IMAGE'), (4, 'TXT'), (5, 'HTML'), (6, 'EMAIL')], default=0)),
                ('ai_uploaded_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('signed_url', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('mistral_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created', related_query_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_deleted', related_query_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated', related_query_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Upload Record',
                'verbose_name_plural': 'File Upload Records',
                'db_table': 'file_upload_records',
            },
        ),
    ]
