# Generated by Django 5.2.1 on 2025-06-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadrecord',
            name='client_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
